
debug: false

api:
  http:
    bind_ip: 127.0.0.1
    port: 9434

net:
  mode: eth
  eth:
    port: 8545
    url: 127.0.0.1
  http:
    listen_port: 9001
    listen_url: 127.0.0.1
    server_port: 9001
    server_url: 127.0.0.1
  standalone:
    client_number: 5

ipfs:
  enabled: false
  addr: /dns/localhost/tcp/5001/http